/*
#include <stdio.h>
#include<stdlib.h>

int g,l,h,c,n;
char line[80];
int main(void)
{
 while(1) {*/
    /*not really*/
   /* g = rand() % 100 + 1;
    l = 0;
    h = 100;
    c = 0;
    printf("%d",g);
    while(1) {
       printf("Bounds %d - %d\n",l,h);
       printf("value[%d]? ",c);
       ++c;
      fgets(line,sizeof(line),stdin);
      sscanf(line,"%d",&n);
      if(n == g)
         break;
      if( n > g)
         l = n;
      else
         h = n;
    }
    printf("Bingo\n");
 }
 return 0;
}*/

/*********************************************************/
/* readable and deciperable solution of the above program*/
/*GUess?????? who's back back again***********************/
/* a simple guess game
A simple number is chosen randomly between the bounds****
upper bound is 100 and lower bounnd is 0;*************** 
a player wins if he guesses right (guess who's back)
else bounds are adjusted as per further guess***********
number is generated by rand()%100.
**********************************************************/

#include <stdio.h>
#include <stdlib.h>

int number_to_guess;
int low_limit;
int high_limit;
int guess_count;
int player_number;
char line[80];

int main(void)
{
   while(1)  {
      printf("\n\n**********Guess who's back; back again!!!!!\n\n");
      /*
       * Not a pure random number, 
       */
      number_to_guess = rand() % 100 + 1;
      
      /*initalizes a variable for the loop*/
      low_limit = 0;
      high_limit = 100;
      guess_count = 0;
      
      while(1)  {
         /* tell the user what are the bounds and get his guess*/
         /*Guess who's back; back again*/
         
         printf("lower bound %d - upper bound %d", low_limit, high_limit);
         printf("Value[%d]?", guess_count);

         ++guess_count;
         	
         fgets(line, sizeof(line), stdin);
         sscanf(line," %d", &player_number);
         
         /*did he guess right(Guess who's back; back again)*/
         if(player_number == number_to_guess)
             break;
          
         if(player_number < number_to_guess)
             low_limit = player_number;
         else
             high_limit = player_number;
        
      }
      
      printf("\n\n*********Bingo********\n Shady's back; back again!\n\n");
   }
}  
